# Generated by Django 3.1.5 on 2021-03-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210313_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='prfile_image',
            field=models.ImageField(blank=True, upload_to='ProfileImg/'),
        ),
    ]
