# Generated by Django 3.1.5 on 2021-03-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210313_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_city',
            field=models.CharField(max_length=100),
        ),
    ]
