# Generated by Django 3.1.5 on 2021-03-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210315_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
